### ISSUE TITLE
Which DAISY player was this tested on?

### ISSUE THREAD

**Issue by ssb22** [Memotech-Bill/MakeDaisy#1]
Hi, thanks for publishing this.  Would it be possible to document which model of DAISY player your father played these on?

Also I have a couple of follow-up questions if you don't mind:
1. Are you using `ISO-8859-1` encoding because `UTF-8` didn't work on that device, or was this not tested (maybe you never had to cope with non-ASCII characters in a title and that's OK, just want to know...)
2. Was 56k the highest bitrate that device could handle, or just a reasonable choice of bitrate for CBR re-coding of speech? (asking because I'm wondering what to do about recordings that have music as well)
3. Was the device unable to handle any sample rate other than 44.1kHz?
4. Did you ever test without `--strictly-enforce-ISO` and/or without `-t` (I'm particularly surprised `-t` is needed to suppress a bit of info at the start of the file: was the player really that fussy?)

Thanks!  I'm trying to figure out the limitations of different DAISY players and the best LAME parameters for [Anemone](http://ssb22.user.srcf.net/indexer/anemone.html).

**Comment by ssb22** [comment]
Hi, further to the above I've checked the LAME source and it seems `--strictly-enforce-ISO` will have no effect on a 44.1kHz 56kbit MP3 file anyway.  What it does is reduce the theoretical maximum bit reservoir of each frame that's not using its full bit allocation, but the 1152-sample frame size at those parameters is only 1463 bits anyway, which is nowhere near the limit so the strict option *should* have no effect.  It's different at other sample rates, but at 44.1kHz it doesn't seem `--strictly-enforce-ISO` matters until we get to 320kbps.

So my *guess* is you saw this option in the man page and thought "might as well have that", which is fair enough.  (But if you actually tested without this option and it didn't work until you put the option in, then something is seriously wrong with my understanding of the LAME code I just looked at :)

**Comment by Memotech-Bill** [comment]
The resulting DAISY CDs were used in a Victor Reader Classic (Visuade, Model 101 VRC) supplied by the RNIB.

It is many years since I worked on this. The files were not posted to this repository until some years later.

I was working from the DAISY specification (v2 if I remember correctly). Also comparing with DAISY CDs from the RNIB. At the time I was just interested in producing something that worked.

**Comment by Memotech-Bill** [comment]
>     1. Are you using `ISO-8859-1` encoding because `UTF-8` didn't work on that device, or was this not tested (maybe you never had to cope with non-ASCII characters in a title and that's OK, just want to know...)
I would guess because the RNIB CDs I used as reference had that encoding.
 
>     2. Was 56k the highest bitrate that device could handle, or just a reasonable choice of bitrate for CBR re-coding of speech? (asking because I'm wondering what to do about recordings that have music as well)
Don't remember. Possibly from the DAISY spec.
 
>     3. Was the device unable to handle any sample rate other than 44.1kHz?
Don't remember. However this is probably the reason I had to trans-code the files.
 
>     4. Did you ever test without `--strictly-enforce-ISO` and/or without `-t` (I'm particularly surprised `-t` is needed to suppress a bit of info at the start of the file: was the player really that fussy?)
Don't remember. Possibly never tested.

**Comment by ssb22** [comment]
Thanks so much, this is a useful data point!  For reference the [Daisy 2.02 spec](https://daisy.org/activities/standards/daisy/daisy-2/daisy-format-2-02-specification/) says "Bitrates: all, Sampling frequencies: all, No of channels: 1 or 2 (mono or stereo)" with a note that VBR might not work on all players (e.g. FSReader's navigation by subheadings and paragraphs starts jumping to the wrong places if you use VBR, which is why I recode to CBR) but I think some players might be more limited than what the spec says when it comes to bitrate and channels too.  Still testing with help from various people who have different players.  Not had a Victor Classic test yet, only the later Victor Stream model.
